# Generated by Django 4.1.7 on 2023-04-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookAdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(max_length=100),
        ),
    ]
